"""empty message

Revision ID: f044376c2a6e
Revises: f04034e2ac61
Create Date: 2016-03-31 20:23:10.086458

"""

# revision identifiers, used by Alembic.
revision = 'f044376c2a6e'
down_revision = 'f04034e2ac61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'author_id')
    ### end Alembic commands ###
